#include "WinUser2/WinUser2.h"
#include "DXGIImmersiveSwapchain/dxgiimmersiveswapchain.h"
#include <windowsx.h>

typedef struct tagSERVERLAUNCHSYNACK {
  DWORD   dwHostThreadId;
  HANDLE  hServerAck;
  HWND    hServer;

} SERVERLAUNCHSYNACK, * LPSERVERLAUNCHSYNACK;

static
ATOM FORCEINLINE WINAPI
RegisterServerClass(
    void
    );

static
DWORD FORCEINLINE APIPRIVATE
ServerThread(
    LPVOID lpvlsa
    );

static
HWND FORCEINLINE CALLBACK
OnServerCreateWindow(
    HWND hWnd,
    LPCREATEWINDOWPARAMS lpcwp
    );

static
BOOL PFORCEINLINE CALLBACK
OnServerDestroyWindow(
    HWND hWnd,
    HWND hWndTarget
    );

static
BOOL CFORCEINLINE CALLBACK
OnNCCreate(
    HWND           hWnd,
    LPCREATESTRUCT lpCreateStruct
    );

static
DWORD FORCEINLINE APIPRIVATE
ServerThread(
    LPVOID lpvlsa)
{
    LPSERVERLAUNCHSYNACK launchSynAck = (LPSERVERLAUNCHSYNACK)lpvlsa;

    DWORD dwHostThreadId = launchSynAck->dwHostThreadId;
    launchSynAck->hServer = CreateWindowEx(WS_EX_TOOLWINDOW, WC_WINDOWSERVER, HWNDSERVER_CLASS, WS_OVERLAPPED, 0, 0, 0, 0, 0, 0, 0, 0);
    
    SetEvent(launchSynAck->hServerAck);

    for(;;)
    {
        MSG Message;
        GetMessage(&Message, 0, 0, 0);
        TranslateMessage(&Message);
        if((Message.message == WM_CHAR)    ||
           (Message.message == WM_KEYDOWN) ||
           (Message.message == WM_QUIT)    ||
           (Message.message == WM_PAINT))
           //(Message.message == WM_PAINT))
        {
            PostThreadMessage(dwHostThreadId, Message.message, Message.wParam, Message.lParam);
        }
        else
        {
            DispatchMessage(&Message);
        }
    }

    //ExitThread(EXIT_SUCCESS);
}

static
HWND FORCEINLINE CALLBACK
OnServerCreateWindow(
    HWND hWnd,
    LPCREATEWINDOWPARAMS lpcwp)
{
    UNREFERENCED_PARAMETER(hWnd);

    return CreateWindowEx(lpcwp->dwExStyle,
                          lpcwp->lpClassName,
                          lpcwp->lpWindowName,
                          lpcwp->dwStyle,
                          lpcwp->X,
                          lpcwp->Y,
                          lpcwp->nWidth,
                          lpcwp->nHeight,
                          lpcwp->hWndParent,
                          lpcwp->hMenu,
                          lpcwp->hInstance,
                          lpcwp->lpParam);
}

static
BOOL CFORCEINLINE CALLBACK
OnServerDestroyWindow(
    HWND hWnd,
    HWND hWndTarget)
{
    UNREFERENCED_PARAMETER(hWnd);
    return DestroyWindow(hWndTarget);
}

static
BOOL CFORCEINLINE CALLBACK
OnNCCreate(
    HWND           hWnd,
    LPCREATESTRUCT lpCreateStruct)
{
    LONG_PTR offset;

    SetLastError(NO_ERROR);
    offset = SetWindowLongPtr(hWnd, GWLP_USERDATA, (LONG_PTR)lpCreateStruct->lpCreateParams);

    if ((offset == 0) && (NO_ERROR != GetLastError()))
      return FALSE;

    return FORWARD_WM_NCCREATE(hWnd, lpCreateStruct, DefWindowProc);
}

BOOL SetWindowOwner(HWND hWnd, HWND hWndOwner)
{
    LONG_PTR offset;

    SetLastError(NO_ERROR);
    offset = SetWindowLongPtr(hWnd, GWLP_HWNDPARENT, hWndOwner);
    
    return (0 == offset) && (NO_ERROR != GetLastError());
}

BOOL SetProcessEcoQoS(DWORD dwProcessId)
{
    HANDLE hProcess;
  
    if (hProcess = OpenProcess(PROCESS_SET_INFORMATION, FALSE, dwProcessId))
    {
      PROCESS_POWER_THROTTLING_STATE PowerThrottling;
      RtlZeroMemory(&PowerThrottling, sizeof(PowerThrottling));

      PowerThrottling.Version = PROCESS_POWER_THROTTLING_CURRENT_VERSION;
      PowerThrottling.ControlMask = PROCESS_POWER_THROTTLING_EXECUTION_SPEED;
      PowerThrottling.StateMask = PROCESS_POWER_THROTTLING_EXECUTION_SPEED;
    
      return SetProcessInformation(hProcess, ProcessPowerThrottling, &PowerThrottling, sizeof(PowerThrottling));
    }
    
    return FALSE;
}

BOOL SetThreadEcoQoS(DWORD dwThreadId)
{
    HANDLE hThread;
  
    if (hThread = OpenThread(THREAD_SET_INFORMATION, FALSE, dwThreadId))
    {
      PROCESS_POWER_THROTTLING_STATE PowerThrottling;
      RtlZeroMemory(&PowerThrottling, sizeof(PowerThrottling));

      PowerThrottling.Version = PROCESS_POWER_THROTTLING_CURRENT_VERSION;
      PowerThrottling.ControlMask = PROCESS_POWER_THROTTLING_EXECUTION_SPEED;
      PowerThrottling.StateMask = PROCESS_POWER_THROTTLING_EXECUTION_SPEED;
    
      return SetThreadInformation(hThread, ThreadPowerThrottling, &PowerThrottling, sizeof(PowerThrottling));
    }
    
    return FALSE;
}

BOOL InMenu(void)
{
    GUITHREADINFO gti = { sizeof(gti) };

    if (GetGUIThreadInfo(GetCurrentThreadId(), &gti))
      return (GUI_INMENUMODE | GUI_SYSTEMMENUMODE | GUI_POPUPMENUMODE) & gti.flags;

    return FALSE;
}

HMENU LoadPopupMenu(HINSTANCE hInstance, LPCTSTR lpMenuName)
{
    HMENU hMenu;
    HMENU hSubMenu;

    if (hMenu = hSubMenu = LoadMenu(hInstance, lpMenuName))
      hSubMenu = GetSubMenu(hMenu, 0);

    return hSubMenu;
}

void ForceTimerMessagesToBeCreatedIfNecessary(LPMSG lpMsg)
{
    PeekMessage(lpMsg, NULL, WM_TIMER, WM_TIMER, PM_NOREMOVE);
}

BOOL PumpMessageQueue(HWND hwndPump)
{
    MSG  msg;
    BOOL fQuit = FALSE;
    SecureZeroMemory(&msg, sizeof(msg));

    if (hwndPump && IsWindow(hwndPump))
    {
      while (PeekMessage(&msg, hwndPump, 0, 0, PM_REMOVE | PM_NOYIELD))
      {
        TranslateMessage(&msg);
        DispatchMessage(&msg);

        fQuit |= WM_QUIT == msg.message;
      }

      fQuit |= !IsWindow(hwndPump);
    }

    while (PeekMessage(&msg, 0, 0, 0, PM_REMOVE | PM_NOYIELD))
    {
      TranslateMessage(&msg);
      DispatchMessage(&msg);
    }
    
    return !fQuit;
}

#include "ImmersiveWindow/framework.h"
#include "ImmersiveWindow/windowsx2.h"

EXTERN_C
BOOL FORCEINLINE
InitAllCommonControls(
    VOID)
{
    INITCOMMONCONTROLSEX icex = { sizeof(icex) };

    icex.dwICC =
      ICC_LISTVIEW_CLASSES   |
      ICC_TREEVIEW_CLASSES   |
      ICC_BAR_CLASSES        |
      ICC_TAB_CLASSES        |
      ICC_UPDOWN_CLASS       |
      ICC_PROGRESS_CLASS     |
      ICC_HOTKEY_CLASS       |
      ICC_DATE_CLASSES       |
      ICC_WIN95_CLASSES      |
      ICC_USEREX_CLASSES     |
      ICC_COOL_CLASSES       |
      ICC_INTERNET_CLASSES   |
      ICC_PAGESCROLLER_CLASS |
      ICC_NATIVEFNTCTL_CLASS |
      ICC_STANDARD_CLASSES   |
      ICC_LINK_CLASS;

    InitCommonControls();
    
    return InitCommonControlsEx(&icex);
}

EXTERN_C
BOOL CFORCEINLINE
MyStrEquals(
    LPCTSTR lpszLeft,
    LPCTSTR lpszRight)
{
    BOOL fTerminate = (0 == *lpszLeft) || (0 == *lpszRight);

    while (!fTerminate)
    {
      if (*(lpszLeft++) != *(lpszRight++))
        break;

      fTerminate = (0 == *lpszLeft) || (0 == *lpszRight);
    }

    return (0 == *lpszLeft) && (0 == *lpszRight);
}

EXTERN_C
BOOL CFORCEINLINE
IsMaximizedEx(
    HWND hwnd)
{
  WINDOWPLACEMENT wp = { sizeof(wp) };

  if (!GetWindowPlacement(hwnd, &wp))
    return FALSE;

  return SW_MAXIMIZE == wp.showCmd;
}

EXTERN_C
BOOL CFORCEINLINE
GetWindowBorders(
    HWND   hwnd,
    LPSIZE lpsz)
{
  if (lpsz)
  {
    const UINT c_nDpi       = GetDpiForWindow(hwnd);
    const LONG c_cxFrame    = GetSystemMetricsForDpi(SM_CXFRAME, c_nDpi);
    const LONG c_cyFrame    = GetSystemMetricsForDpi(SM_CYFRAME, c_nDpi);
    const LONG c_cxyPadding = GetSystemMetricsForDpi(SM_CXPADDEDBORDER, c_nDpi);

    lpsz->cx = c_cxFrame + c_cxyPadding;
    lpsz->cy = c_cyFrame + c_cxyPadding;

    return TRUE;
  }

  return FALSE;
}

EXTERN_C
BOOL FORCEINLINE
GetCaptionRect(
    HWND   hWnd,
    LPRECT lprcCaption)
{
    UINT nDpi = GetDpiForWindow(hWnd);
    int nHeight = MulDiv(30, (int)nDpi, 96);

    if (GetWindowRect(hWnd, lprcCaption))
    {
      SIZE border;
      const BOOL c_fIsMaximized = IsMaximized(hWnd);

      GetWindowBorders(hWnd, &border);

      lprcCaption->top    += (border.cy * !c_fIsMaximized);
      lprcCaption->left   += (border.cx * !c_fIsMaximized);
      lprcCaption->right  -= (border.cx * !c_fIsMaximized);
      lprcCaption->bottom = lprcCaption->top + nHeight;

      return TRUE;
    }

    return FALSE;
}

EXTERN_C
LPCTSTR FORCEINLINE
DecipherMessage(
    UINT uMsg)
{
#define MSG2MSG(x)     \
    case x:            \
        return TEXT(#x) TEXT("\n");

  switch (uMsg) {
  MSG2MSG(WM_NULL)
  MSG2MSG(WM_UAHDESTROYWINDOW)
  MSG2MSG(WM_UAHDRAWMENU)
  MSG2MSG(WM_UAHDRAWMENUITEM)
  MSG2MSG(WM_UAHINITMENU)
  MSG2MSG(WM_UAHMEASUREMENUITEM)
  MSG2MSG(WM_UAHNCPAINTMENUPOPUP)
  MSG2MSG(WM_UAHUPDATE)
  MSG2MSG(WM_NCUAHDRAWCAPTION)
  MSG2MSG(WM_NCUAHDRAWFRAME)
  MSG2MSG(EM_MSGMAX)
  MSG2MSG(WM_SYSTIMER)
  MSG2MSG(WM_GETISHELLBROWSER)
  MSG2MSG(WM_SYSMENU)
  MSG2MSG(WM_THEMECHANGED)
  MSG2MSG(WM_CREATE)
  MSG2MSG(WM_DESTROY)
  MSG2MSG(WM_MOVE)
  MSG2MSG(WM_SIZE)
  MSG2MSG(WM_ACTIVATE)
  MSG2MSG(WM_SETFOCUS)
  MSG2MSG(WM_KILLFOCUS)
  MSG2MSG(WM_ENABLE)
  MSG2MSG(WM_SETREDRAW)
  MSG2MSG(WM_SETTEXT)
  MSG2MSG(WM_GETTEXT)
  MSG2MSG(WM_GETTEXTLENGTH)
  MSG2MSG(WM_PAINT)
  MSG2MSG(WM_CLOSE)
  MSG2MSG(WM_QUERYENDSESSION)
  MSG2MSG(WM_QUIT)
  MSG2MSG(WM_QUERYOPEN)
  MSG2MSG(WM_ERASEBKGND)
  MSG2MSG(WM_SYSCOLORCHANGE)
  MSG2MSG(WM_ENDSESSION)
  MSG2MSG(WM_SHOWWINDOW)
  MSG2MSG(WM_CTLCOLOR)
  MSG2MSG(WM_WININICHANGE)
  MSG2MSG(WM_DEVMODECHANGE)
  MSG2MSG(WM_ACTIVATEAPP)
  MSG2MSG(WM_FONTCHANGE)
  MSG2MSG(WM_TIMECHANGE)
  MSG2MSG(WM_CANCELMODE)
  MSG2MSG(WM_SETCURSOR)
  MSG2MSG(WM_MOUSEACTIVATE)
  MSG2MSG(WM_CHILDACTIVATE)
  MSG2MSG(WM_QUEUESYNC)
  MSG2MSG(WM_GETMINMAXINFO)
  MSG2MSG(WM_PAINTICON)
  MSG2MSG(WM_ICONERASEBKGND)
  MSG2MSG(WM_NEXTDLGCTL)
  MSG2MSG(WM_SPOOLERSTATUS)
  MSG2MSG(WM_DRAWITEM)
  MSG2MSG(WM_MEASUREITEM)
  MSG2MSG(WM_DELETEITEM)
  MSG2MSG(WM_VKEYTOITEM)
  MSG2MSG(WM_CHARTOITEM)
  MSG2MSG(WM_SETFONT)
  MSG2MSG(WM_GETFONT)
  MSG2MSG(WM_SETHOTKEY)
  MSG2MSG(WM_GETHOTKEY)
  MSG2MSG(WM_QUERYDRAGICON)
  MSG2MSG(WM_COMPAREITEM)
  MSG2MSG(WM_GETOBJECT)
  MSG2MSG(WM_COMPACTING)
  MSG2MSG(WM_COMMNOTIFY)
  MSG2MSG(WM_WINDOWPOSCHANGING)
  MSG2MSG(WM_WINDOWPOSCHANGED)
  MSG2MSG(WM_POWER)
  //MSG2MSG(WM_COPYGLOBALDATA)
  MSG2MSG(WM_COPYDATA)
  MSG2MSG(WM_CANCELJOURNAL)
  MSG2MSG(WM_NOTIFY)
  MSG2MSG(WM_INPUTLANGCHANGEREQUEST)
  MSG2MSG(WM_INPUTLANGCHANGE)
  MSG2MSG(WM_TCARD)
  MSG2MSG(WM_HELP)
  MSG2MSG(WM_USERCHANGED)
  MSG2MSG(WM_NOTIFYFORMAT)
  MSG2MSG(WM_CONTEXTMENU)
  MSG2MSG(WM_STYLECHANGING)
  MSG2MSG(WM_STYLECHANGED)
  MSG2MSG(WM_DISPLAYCHANGE)
  MSG2MSG(WM_GETICON)
  MSG2MSG(WM_SETICON)
  MSG2MSG(WM_NCCREATE)
  MSG2MSG(WM_NCDESTROY)
  MSG2MSG(WM_NCCALCSIZE)
  MSG2MSG(WM_NCHITTEST)
  MSG2MSG(WM_NCPAINT)
  MSG2MSG(WM_NCACTIVATE)
  MSG2MSG(WM_GETDLGCODE)
  MSG2MSG(WM_SYNCPAINT)
  MSG2MSG(WM_NCMOUSEMOVE)
  MSG2MSG(WM_NCLBUTTONDOWN)
  MSG2MSG(WM_NCLBUTTONUP)
  MSG2MSG(WM_NCLBUTTONDBLCLK)
  MSG2MSG(WM_NCRBUTTONDOWN)
  MSG2MSG(WM_NCRBUTTONUP)
  MSG2MSG(WM_NCRBUTTONDBLCLK)
  MSG2MSG(WM_NCMBUTTONDOWN)
  MSG2MSG(WM_NCMBUTTONUP)
  MSG2MSG(WM_NCMBUTTONDBLCLK)
  MSG2MSG(WM_NCXBUTTONDOWN)
  MSG2MSG(WM_NCXBUTTONUP)
  MSG2MSG(WM_NCXBUTTONDBLCLK)
  MSG2MSG(EM_GETSEL)
  MSG2MSG(EM_SETSEL)
  MSG2MSG(EM_GETRECT)
  MSG2MSG(EM_SETRECT)
  MSG2MSG(EM_SETRECTNP)
  MSG2MSG(EM_SCROLL)
  MSG2MSG(EM_LINESCROLL)
  MSG2MSG(EM_SCROLLCARET)
  MSG2MSG(EM_GETMODIFY)
  MSG2MSG(EM_SETMODIFY)
  MSG2MSG(EM_GETLINECOUNT)
  MSG2MSG(EM_LINEINDEX)
  MSG2MSG(EM_SETHANDLE)
  MSG2MSG(EM_GETHANDLE)
  MSG2MSG(EM_GETTHUMB)
  MSG2MSG(EM_LINELENGTH)
  MSG2MSG(EM_REPLACESEL)
  //MSG2MSG(EM_SETFONT)
  MSG2MSG(EM_GETLINE)
  MSG2MSG(EM_LIMITTEXT)
  //MSG2MSG(EM_SETLIMITTEXT)
  MSG2MSG(EM_CANUNDO)
  MSG2MSG(EM_UNDO)
  MSG2MSG(EM_FMTLINES)
  MSG2MSG(EM_LINEFROMCHAR)
  //MSG2MSG(EM_SETWORDBREAK)
  MSG2MSG(EM_SETTABSTOPS)
  MSG2MSG(EM_SETPASSWORDCHAR)
  MSG2MSG(EM_EMPTYUNDOBUFFER)
  MSG2MSG(EM_GETFIRSTVISIBLELINE)
  MSG2MSG(EM_SETREADONLY)
  MSG2MSG(EM_SETWORDBREAKPROC)
  MSG2MSG(EM_GETWORDBREAKPROC)
  MSG2MSG(EM_GETPASSWORDCHAR)
  MSG2MSG(EM_SETMARGINS)
  MSG2MSG(EM_GETMARGINS)
  MSG2MSG(EM_GETLIMITTEXT)
  MSG2MSG(EM_POSFROMCHAR)
  MSG2MSG(EM_CHARFROMPOS)
  MSG2MSG(EM_SETIMESTATUS)
  MSG2MSG(EM_GETIMESTATUS)
  MSG2MSG(SBM_SETPOS)
  MSG2MSG(SBM_GETPOS)
  MSG2MSG(SBM_SETRANGE)
  MSG2MSG(SBM_GETRANGE)
  MSG2MSG(SBM_ENABLE_ARROWS)
  MSG2MSG(SBM_SETRANGEREDRAW)
  MSG2MSG(SBM_SETSCROLLINFO)
  MSG2MSG(SBM_GETSCROLLINFO)
  MSG2MSG(SBM_GETSCROLLBARINFO)
  MSG2MSG(BM_GETCHECK)
  MSG2MSG(BM_SETCHECK)
  MSG2MSG(BM_GETSTATE)
  MSG2MSG(BM_SETSTATE)
  MSG2MSG(BM_SETSTYLE)
  MSG2MSG(BM_CLICK)
  MSG2MSG(BM_GETIMAGE)
  MSG2MSG(BM_SETIMAGE)
  MSG2MSG(BM_SETDONTCLICK)
  MSG2MSG(WM_INPUT)
  MSG2MSG(WM_KEYDOWN)
  //MSG2MSG(WM_KEYFIRST)
  MSG2MSG(WM_KEYUP)
  MSG2MSG(WM_CHAR)
  MSG2MSG(WM_DEADCHAR)
  MSG2MSG(WM_SYSKEYDOWN)
  MSG2MSG(WM_SYSKEYUP)
  MSG2MSG(WM_SYSCHAR)
  MSG2MSG(WM_SYSDEADCHAR)
  //MSG2MSG(WM_UNICHAR / WM_KEYLAST)
  //MSG2MSG(WM_WNT_CONVERTREQUESTEX)
  //MSG2MSG(WM_CONVERTREQUEST)
  //MSG2MSG(WM_CONVERTRESULT)
  //MSG2MSG(WM_INTERIM)
  MSG2MSG(WM_IME_STARTCOMPOSITION)
  MSG2MSG(WM_IME_ENDCOMPOSITION)
  MSG2MSG(WM_IME_COMPOSITION)
  //MSG2MSG(WM_IME_KEYLAST)
  MSG2MSG(WM_INITDIALOG)
  MSG2MSG(WM_COMMAND)
  MSG2MSG(WM_SYSCOMMAND)
  MSG2MSG(WM_TIMER)
  MSG2MSG(WM_HSCROLL)
  MSG2MSG(WM_VSCROLL)
  MSG2MSG(WM_INITMENU)
  MSG2MSG(WM_INITMENUPOPUP)
  //MSG2MSG(WM_SYSTIMER)
  MSG2MSG(WM_MENUSELECT)
  MSG2MSG(WM_MENUCHAR)
  MSG2MSG(WM_ENTERIDLE)
  MSG2MSG(WM_MENURBUTTONUP)
  MSG2MSG(WM_MENUDRAG)
  MSG2MSG(WM_MENUGETOBJECT)
  MSG2MSG(WM_UNINITMENUPOPUP)
  MSG2MSG(WM_MENUCOMMAND)
  MSG2MSG(WM_CHANGEUISTATE)
  MSG2MSG(WM_UPDATEUISTATE)
  MSG2MSG(WM_QUERYUISTATE)
  //MSG2MSG(WM_LBTRACKPOINT)
  MSG2MSG(WM_CTLCOLORMSGBOX)
  MSG2MSG(WM_CTLCOLOREDIT)
  MSG2MSG(WM_CTLCOLORLISTBOX)
  MSG2MSG(WM_CTLCOLORBTN)
  MSG2MSG(WM_CTLCOLORDLG)
  MSG2MSG(WM_CTLCOLORSCROLLBAR)
  MSG2MSG(WM_CTLCOLORSTATIC)
  MSG2MSG(CB_GETEDITSEL)
  MSG2MSG(CB_LIMITTEXT)
  MSG2MSG(CB_SETEDITSEL)
  MSG2MSG(CB_ADDSTRING)
  MSG2MSG(CB_DELETESTRING)
  MSG2MSG(CB_DIR)
  MSG2MSG(CB_GETCOUNT)
  MSG2MSG(CB_GETCURSEL)
  MSG2MSG(CB_GETLBTEXT)
  MSG2MSG(CB_GETLBTEXTLEN)
  MSG2MSG(CB_INSERTSTRING)
  MSG2MSG(CB_RESETCONTENT)
  MSG2MSG(CB_FINDSTRING)
  MSG2MSG(CB_SELECTSTRING)
  MSG2MSG(CB_SETCURSEL)
  MSG2MSG(CB_SHOWDROPDOWN)
  MSG2MSG(CB_GETITEMDATA)
  MSG2MSG(CB_SETITEMDATA)
  MSG2MSG(CB_GETDROPPEDCONTROLRECT)
  MSG2MSG(CB_SETITEMHEIGHT)
  MSG2MSG(CB_GETITEMHEIGHT)
  MSG2MSG(CB_SETEXTENDEDUI)
  MSG2MSG(CB_GETEXTENDEDUI)
  MSG2MSG(CB_GETDROPPEDSTATE)
  MSG2MSG(CB_FINDSTRINGEXACT)
  MSG2MSG(CB_SETLOCALE)
  MSG2MSG(CB_GETLOCALE)
  MSG2MSG(CB_GETTOPINDEX)
  MSG2MSG(CB_SETTOPINDEX)
  MSG2MSG(CB_GETHORIZONTALEXTENT)
  MSG2MSG(CB_SETHORIZONTALEXTENT)
  MSG2MSG(CB_GETDROPPEDWIDTH)
  MSG2MSG(CB_SETDROPPEDWIDTH)
  MSG2MSG(CB_INITSTORAGE)
  //MSG2MSG(CB_MULTIPLEADDSTRING)
  MSG2MSG(CB_GETCOMBOBOXINFO)
  MSG2MSG(CB_MSGMAX)
  //MSG2MSG(WM_MOUSEFIRST)
  MSG2MSG(WM_MOUSEMOVE)
  MSG2MSG(WM_LBUTTONDOWN)
  MSG2MSG(WM_LBUTTONUP)
  MSG2MSG(WM_LBUTTONDBLCLK)
  MSG2MSG(WM_RBUTTONDOWN)
  MSG2MSG(WM_RBUTTONUP)
  MSG2MSG(WM_RBUTTONDBLCLK)
  MSG2MSG(WM_MBUTTONDOWN)
  MSG2MSG(WM_MBUTTONUP)
  MSG2MSG(WM_MBUTTONDBLCLK)
  MSG2MSG(WM_MOUSELAST)
  MSG2MSG(WM_MOUSEWHEEL)
  MSG2MSG(WM_XBUTTONDOWN)
  MSG2MSG(WM_XBUTTONUP)
  MSG2MSG(WM_XBUTTONDBLCLK)
  //MSG2MSG(WM_MOUSEHWHEEL)
  MSG2MSG(WM_PARENTNOTIFY)
  MSG2MSG(WM_ENTERMENULOOP)
  MSG2MSG(WM_EXITMENULOOP)
  MSG2MSG(WM_NEXTMENU)
  MSG2MSG(WM_SIZING)
  MSG2MSG(WM_CAPTURECHANGED)
  MSG2MSG(WM_MOVING)
  MSG2MSG(WM_POWERBROADCAST)
  MSG2MSG(WM_DEVICECHANGE)
  MSG2MSG(WM_MDICREATE)
  MSG2MSG(WM_MDIDESTROY)
  MSG2MSG(WM_MDIACTIVATE)
  MSG2MSG(WM_MDIRESTORE)
  MSG2MSG(WM_MDINEXT)
  MSG2MSG(WM_MDIMAXIMIZE)
  MSG2MSG(WM_MDITILE)
  MSG2MSG(WM_MDICASCADE)
  MSG2MSG(WM_MDIICONARRANGE)
  MSG2MSG(WM_MDIGETACTIVE)
  MSG2MSG(WM_MDISETMENU)
  MSG2MSG(WM_ENTERSIZEMOVE)
  MSG2MSG(WM_EXITSIZEMOVE)
  MSG2MSG(WM_DROPFILES)
  MSG2MSG(WM_MDIREFRESHMENU)
  //MSG2MSG(WM_IME_REPORT)
  MSG2MSG(WM_IME_SETCONTEXT)
  MSG2MSG(WM_IME_NOTIFY)
  MSG2MSG(WM_IME_CONTROL)
  MSG2MSG(WM_IME_COMPOSITIONFULL)
  MSG2MSG(WM_IME_SELECT)
  MSG2MSG(WM_IME_CHAR)
  MSG2MSG(WM_IME_REQUEST)
  //MSG2MSG(WM_IMEKEYDOWN)
  MSG2MSG(WM_IME_KEYDOWN)
  //MSG2MSG(WM_IMEKEYUP)
  MSG2MSG(WM_IME_KEYUP)
  MSG2MSG(WM_NCMOUSEHOVER)
  MSG2MSG(WM_MOUSEHOVER)
  MSG2MSG(WM_NCMOUSELEAVE)
  MSG2MSG(WM_MOUSELEAVE)
  //MSG2MSG(WM_TABLET_DEFBASE)
  MSG2MSG(WM_TABLET_FIRST)
  //MSG2MSG(WM_TABLET_ADDED)
  //MSG2MSG(WM_TABLET_DELETED)
  //MSG2MSG(WM_TABLET_FLICK)
  //MSG2MSG(WM_TABLET_QUERYSYSTEMGESTURESTATUS)
  MSG2MSG(WM_TABLET_LAST)
  MSG2MSG(WM_CUT)
  MSG2MSG(WM_COPY)
  MSG2MSG(WM_PASTE)
  MSG2MSG(WM_CLEAR)
  MSG2MSG(WM_UNDO)
  MSG2MSG(WM_RENDERFORMAT)
  MSG2MSG(WM_RENDERALLFORMATS)
  MSG2MSG(WM_DESTROYCLIPBOARD)
  MSG2MSG(WM_DRAWCLIPBOARD)
  MSG2MSG(WM_PAINTCLIPBOARD)
  MSG2MSG(WM_VSCROLLCLIPBOARD)
  MSG2MSG(WM_SIZECLIPBOARD)
  MSG2MSG(WM_ASKCBFORMATNAME)
  MSG2MSG(WM_CHANGECBCHAIN)
  MSG2MSG(WM_HSCROLLCLIPBOARD)
  MSG2MSG(WM_QUERYNEWPALETTE)
  MSG2MSG(WM_PALETTEISCHANGING)
  MSG2MSG(WM_PALETTECHANGED)
  MSG2MSG(WM_HOTKEY)
  MSG2MSG(WM_PRINT)
  MSG2MSG(WM_PRINTCLIENT)
  MSG2MSG(WM_APPCOMMAND)
  MSG2MSG(WM_HANDHELDFIRST)
  MSG2MSG(WM_HANDHELDLAST)
  MSG2MSG(WM_AFXFIRST)
  MSG2MSG(WM_AFXLAST)
  MSG2MSG(WM_PENWINFIRST)
  //MSG2MSG(WM_RCRESULT)
  //MSG2MSG(WM_HOOKRCRESULT)
  //MSG2MSG(WM_GLOBALRCCHANGE)
  //MSG2MSG(WM_PENMISCINFO)
  //MSG2MSG(WM_SKB)
  //MSG2MSG(WM_HEDITCTL)
  //MSG2MSG(WM_PENCTL)
  //MSG2MSG(WM_PENMISC)
  //MSG2MSG(WM_CTLINIT)
  //MSG2MSG(WM_PENEVENT)
  MSG2MSG(WM_PENWINLAST)
  //MSG2MSG(DDM_SETFMT)
  MSG2MSG(DM_GETDEFID)
  //MSG2MSG(NIN_SELECT)
  //MSG2MSG(TBM_GETPOS)
  //MSG2MSG(WM_PSD_PAGESETUPDLG)
  //MSG2MSG(WM_USER)
  MSG2MSG(CBEM_INSERTITEMA)
  //MSG2MSG(DDM_DRAW)
  //MSG2MSG(DM_SETDEFID)
  //MSG2MSG(HKM_SETHOTKEY)
  //MSG2MSG(PBM_SETRANGE)
  //MSG2MSG(RB_INSERTBANDA)
  //MSG2MSG(SB_SETTEXTA)
  //MSG2MSG(TB_ENABLEBUTTON)
  //MSG2MSG(TBM_GETRANGEMIN)
  //MSG2MSG(TTM_ACTIVATE)
  ////MSG2MSG(WM_CHOOSEFONT_GETLOGFONT)
  ////MSG2MSG(WM_PSD_FULLPAGERECT)
  //MSG2MSG(CBEM_SETIMAGELIST)
  ////MSG2MSG(DDM_CLOSE)
  //MSG2MSG(DM_REPOSITION)
  //MSG2MSG(HKM_GETHOTKEY)
  //MSG2MSG(PBM_SETPOS)
  //MSG2MSG(RB_DELETEBAND)
  //MSG2MSG(SB_GETTEXTA)
  //MSG2MSG(TB_CHECKBUTTON)
  //MSG2MSG(TBM_GETRANGEMAX)
  ////MSG2MSG(WM_PSD_MINMARGINRECT)
  //MSG2MSG(CBEM_GETIMAGELIST)
  ////MSG2MSG(DDM_BEGIN)
  //MSG2MSG(HKM_SETRULES)
  //MSG2MSG(PBM_DELTAPOS)
  //MSG2MSG(RB_GETBARINFO)
  //MSG2MSG(SB_GETTEXTLENGTHA)
  //MSG2MSG(TBM_GETTIC)
  //MSG2MSG(TB_PRESSBUTTON)
  //MSG2MSG(TTM_SETDELAYTIME)
  ////MSG2MSG(WM_PSD_MARGINRECT)
  //MSG2MSG(CBEM_GETITEMA)
  ////MSG2MSG(DDM_END)
  //MSG2MSG(PBM_SETSTEP)
  //MSG2MSG(RB_SETBARINFO)
  //MSG2MSG(SB_SETPARTS)
  //MSG2MSG(TB_HIDEBUTTON)
  //MSG2MSG(TBM_SETTIC)
  //MSG2MSG(TTM_ADDTOOLA)
  ////MSG2MSG(WM_PSD_GREEKTEXTRECT)
  //MSG2MSG(CBEM_SETITEMA)
  //MSG2MSG(PBM_STEPIT)
  //MSG2MSG(TB_INDETERMINATE)
  //MSG2MSG(TBM_SETPOS)
  //MSG2MSG(TTM_DELTOOLA)
  ////MSG2MSG(WM_PSD_ENVSTAMPRECT)
  //MSG2MSG(CBEM_GETCOMBOCONTROL)
  //MSG2MSG(PBM_SETRANGE32)
  //MSG2MSG(RB_SETBANDINFOA)
  //MSG2MSG(SB_GETPARTS)
  //MSG2MSG(TB_MARKBUTTON)
  //MSG2MSG(TBM_SETRANGE)
  //MSG2MSG(TTM_NEWTOOLRECTA)
  ////MSG2MSG(WM_PSD_YAFULLPAGERECT)
  //MSG2MSG(CBEM_GETEDITCONTROL)
  //MSG2MSG(PBM_GETRANGE)
  //MSG2MSG(RB_SETPARENT)
  //MSG2MSG(SB_GETBORDERS)
  //MSG2MSG(TBM_SETRANGEMIN)
  //MSG2MSG(TTM_RELAYEVENT)
  //MSG2MSG(CBEM_SETEXSTYLE)
  //MSG2MSG(PBM_GETPOS)
  //MSG2MSG(RB_HITTEST)
  //MSG2MSG(SB_SETMINHEIGHT)
  //MSG2MSG(TBM_SETRANGEMAX)
  //MSG2MSG(TTM_GETTOOLINFOA)
  //MSG2MSG(CBEM_GETEXSTYLE)
  //MSG2MSG(CBEM_GETEXTENDEDSTYLE)
  //MSG2MSG(PBM_SETBARCOLOR)
  //MSG2MSG(RB_GETRECT)
  //MSG2MSG(SB_SIMPLE)
  //MSG2MSG(TB_ISBUTTONENABLED)
  //MSG2MSG(TBM_CLEARTICS)
  //MSG2MSG(TTM_SETTOOLINFOA)
  //MSG2MSG(CBEM_HASEDITCHANGED)
  //MSG2MSG(RB_INSERTBANDW)
  //MSG2MSG(SB_GETRECT)
  //MSG2MSG(TB_ISBUTTONCHECKED)
  //MSG2MSG(TBM_SETSEL)
  //MSG2MSG(TTM_HITTESTA)
  ////MSG2MSG(WIZ_QUERYNUMPAGES)
  //MSG2MSG(CBEM_INSERTITEMW)
  //MSG2MSG(RB_SETBANDINFOW)
  //MSG2MSG(SB_SETTEXTW)
  //MSG2MSG(TB_ISBUTTONPRESSED)
  //MSG2MSG(TBM_SETSELSTART)
  //MSG2MSG(TTM_GETTEXTA)
  ////MSG2MSG(WIZ_NEXT)
  //MSG2MSG(CBEM_SETITEMW)
  //MSG2MSG(RB_GETBANDCOUNT)
  //MSG2MSG(SB_GETTEXTLENGTHW)
  //MSG2MSG(TB_ISBUTTONHIDDEN)
  //MSG2MSG(TBM_SETSELEND)
  //MSG2MSG(TTM_UPDATETIPTEXTA)
  ////MSG2MSG(WIZ_PREV)
  //MSG2MSG(CBEM_GETITEMW)
  //MSG2MSG(RB_GETROWCOUNT)
  //MSG2MSG(SB_GETTEXTW)
  //MSG2MSG(TB_ISBUTTONINDETERMINATE)
  //MSG2MSG(TTM_GETTOOLCOUNT)
  //MSG2MSG(CBEM_SETEXTENDEDSTYLE)
  //MSG2MSG(RB_GETROWHEIGHT)
  //MSG2MSG(SB_ISSIMPLE)
  //MSG2MSG(TB_ISBUTTONHIGHLIGHTED)
  //MSG2MSG(TBM_GETPTICS)
  //MSG2MSG(TTM_ENUMTOOLSA)
  //MSG2MSG(SB_SETICON)
  //MSG2MSG(TBM_GETTICPOS)
  //MSG2MSG(TTM_GETCURRENTTOOLA)
  //MSG2MSG(RB_IDTOINDEX)
  //MSG2MSG(SB_SETTIPTEXTA)
  //MSG2MSG(TBM_GETNUMTICS)
  //MSG2MSG(TTM_WINDOWFROMPOINT)
  //MSG2MSG(RB_GETTOOLTIPS)
  //MSG2MSG(SB_SETTIPTEXTW)
  //MSG2MSG(TBM_GETSELSTART)
  //MSG2MSG(TB_SETSTATE)
  //MSG2MSG(TTM_TRACKACTIVATE)
  //MSG2MSG(RB_SETTOOLTIPS)
  //MSG2MSG(SB_GETTIPTEXTA)
  MSG2MSG(TB_GETSTATE)
  //MSG2MSG(TBM_GETSELEND)
  //MSG2MSG(TTM_TRACKPOSITION)
  MSG2MSG(RB_SETBKCOLOR)
  //MSG2MSG(SB_GETTIPTEXTW)
  //MSG2MSG(TB_ADDBITMAP)
  //MSG2MSG(TBM_CLEARSEL)
  //MSG2MSG(TTM_SETTIPBKCOLOR)
  MSG2MSG(RB_GETBKCOLOR)
  //MSG2MSG(SB_GETICON)
  //MSG2MSG(TB_ADDBUTTONSA)
  //MSG2MSG(TBM_SETTICFREQ)
  //MSG2MSG(TTM_SETTIPTEXTCOLOR)
  MSG2MSG(RB_SETTEXTCOLOR)
  //MSG2MSG(TB_INSERTBUTTONA)
  //MSG2MSG(TBM_SETPAGESIZE)
  //MSG2MSG(TTM_GETDELAYTIME)
  MSG2MSG(RB_GETTEXTCOLOR)
  //MSG2MSG(TB_DELETEBUTTON)
  //MSG2MSG(TBM_GETPAGESIZE)
  //MSG2MSG(TTM_GETTIPBKCOLOR)
  MSG2MSG(RB_SIZETORECT)
  //MSG2MSG(TB_GETBUTTON)
  //MSG2MSG(TBM_SETLINESIZE)
  //MSG2MSG(TTM_GETTIPTEXTCOLOR)
  MSG2MSG(RB_BEGINDRAG)
  //MSG2MSG(TB_BUTTONCOUNT)
  //MSG2MSG(TBM_GETLINESIZE)
  //MSG2MSG(TTM_SETMAXTIPWIDTH)
  MSG2MSG(RB_ENDDRAG)
  //MSG2MSG(TB_COMMANDTOINDEX)
  //MSG2MSG(TBM_GETTHUMBRECT)
  //MSG2MSG(TTM_GETMAXTIPWIDTH)
  MSG2MSG(RB_DRAGMOVE)
  //MSG2MSG(TBM_GETCHANNELRECT)
  //MSG2MSG(TB_SAVERESTOREA)
  //MSG2MSG(TTM_SETMARGIN)
  MSG2MSG(RB_GETBARHEIGHT)
  //MSG2MSG(TB_CUSTOMIZE)
  //MSG2MSG(TBM_SETTHUMBLENGTH)
  //MSG2MSG(TTM_GETMARGIN)
  MSG2MSG(RB_GETBANDINFOW)
  //MSG2MSG(TB_ADDSTRINGA)
  //MSG2MSG(TBM_GETTHUMBLENGTH)
  //MSG2MSG(TTM_POP)
  MSG2MSG(RB_GETBANDINFOA)
  //MSG2MSG(TB_GETITEMRECT)
  //MSG2MSG(TBM_SETTOOLTIPS)
  //MSG2MSG(TTM_UPDATE)
  MSG2MSG(RB_MINIMIZEBAND)
  //MSG2MSG(TB_BUTTONSTRUCTSIZE)
  //MSG2MSG(TBM_GETTOOLTIPS)
  //MSG2MSG(TTM_GETBUBBLESIZE)
  MSG2MSG(RB_MAXIMIZEBAND)
  //MSG2MSG(TBM_SETTIPSIDE)
  //MSG2MSG(TB_SETBUTTONSIZE)
  //MSG2MSG(TTM_ADJUSTRECT)
  MSG2MSG(TBM_SETBUDDY)
  //MSG2MSG(TB_SETBITMAPSIZE)
  //MSG2MSG(TTM_SETTITLEA)
  //MSG2MSG(MSG_FTS_JUMP_VA)
  MSG2MSG(TB_AUTOSIZE)
  //MSG2MSG(TBM_GETBUDDY)
  //MSG2MSG(TTM_SETTITLEW)
  MSG2MSG(RB_GETBANDBORDERS)
  //MSG2MSG(MSG_FTS_JUMP_QWORD)
  MSG2MSG(RB_SHOWBAND)
  //MSG2MSG(TB_GETTOOLTIPS)
  //MSG2MSG(MSG_REINDEX_REQUEST)
  MSG2MSG(TB_SETTOOLTIPS)
  //MSG2MSG(MSG_FTS_WHERE_IS_IT)
  MSG2MSG(RB_SETPALETTE)
  //MSG2MSG(TB_SETPARENT)
  MSG2MSG(RB_GETPALETTE)
  MSG2MSG(RB_MOVEBAND)
  //MSG2MSG(TB_SETROWS)
  MSG2MSG(TB_GETROWS)
  MSG2MSG(TB_GETBITMAPFLAGS)
  MSG2MSG(TB_SETCMDID)
  MSG2MSG(RB_PUSHCHEVRON)
  //MSG2MSG(TB_CHANGEBITMAP)
  MSG2MSG(TB_GETBITMAP)
  //MSG2MSG(MSG_GET_DEFFONT)
  MSG2MSG(TB_GETBUTTONTEXTA)
  MSG2MSG(TB_REPLACEBITMAP)
  MSG2MSG(TB_SETINDENT)
  MSG2MSG(TB_SETIMAGELIST)
  MSG2MSG(TB_GETIMAGELIST)
  MSG2MSG(TB_LOADIMAGES)
  //MSG2MSG(EM_CANPASTE)
  //MSG2MSG(TTM_ADDTOOLW)
  //MSG2MSG(EM_DISPLAYBAND)
  MSG2MSG(TB_GETRECT)
  //MSG2MSG(TTM_DELTOOLW)
  //MSG2MSG(EM_EXGETSEL)
  MSG2MSG(TB_SETHOTIMAGELIST)
  //MSG2MSG(TTM_NEWTOOLRECTW)
  //MSG2MSG(EM_EXLIMITTEXT)
  MSG2MSG(TB_GETHOTIMAGELIST)
  //MSG2MSG(TTM_GETTOOLINFOW)
  //MSG2MSG(EM_EXLINEFROMCHAR)
  MSG2MSG(TB_SETDISABLEDIMAGELIST)
  //MSG2MSG(TTM_SETTOOLINFOW)
  //MSG2MSG(EM_EXSETSEL)
  MSG2MSG(TB_GETDISABLEDIMAGELIST)
  //MSG2MSG(TTM_HITTESTW)
  //MSG2MSG(EM_FINDTEXT)
  MSG2MSG(TB_SETSTYLE)
  //MSG2MSG(TTM_GETTEXTW)
  //MSG2MSG(EM_FORMATRANGE)
  MSG2MSG(TB_GETSTYLE)
  //MSG2MSG(TTM_UPDATETIPTEXTW)
  //MSG2MSG(EM_GETCHARFORMAT)
  MSG2MSG(TB_GETBUTTONSIZE)
  //MSG2MSG(TTM_ENUMTOOLSW)
  //MSG2MSG(EM_GETEVENTMASK)
  MSG2MSG(TB_SETBUTTONWIDTH)
  //MSG2MSG(TTM_GETCURRENTTOOLW)
  //MSG2MSG(EM_GETOLEINTERFACE)
  MSG2MSG(TB_SETMAXTEXTROWS)
  //MSG2MSG(EM_GETPARAFORMAT)
  MSG2MSG(TB_GETTEXTROWS)
  //MSG2MSG(EM_GETSELTEXT)
  MSG2MSG(TB_GETOBJECT)
  //MSG2MSG(EM_HIDESELECTION)
  MSG2MSG(TB_GETBUTTONINFOW)
  //MSG2MSG(EM_PASTESPECIAL)
  MSG2MSG(TB_SETBUTTONINFOW)
  //MSG2MSG(EM_REQUESTRESIZE)
  MSG2MSG(TB_GETBUTTONINFOA)
  //MSG2MSG(EM_SELECTIONTYPE)
  MSG2MSG(TB_SETBUTTONINFOA)
  //MSG2MSG(EM_SETBKGNDCOLOR)
  MSG2MSG(TB_INSERTBUTTONW)
  //MSG2MSG(EM_SETCHARFORMAT)
  MSG2MSG(TB_ADDBUTTONSW)
  //MSG2MSG(EM_SETEVENTMASK)
  MSG2MSG(TB_HITTEST)
  //MSG2MSG(EM_SETOLECALLBACK)
  MSG2MSG(TB_SETDRAWTEXTFLAGS)
  //MSG2MSG(EM_SETPARAFORMAT)
  MSG2MSG(TB_GETHOTITEM)
  //MSG2MSG(EM_SETTARGETDEVICE)
  MSG2MSG(TB_SETHOTITEM)
  //MSG2MSG(EM_STREAMIN)
  MSG2MSG(TB_SETANCHORHIGHLIGHT)
  //MSG2MSG(EM_STREAMOUT)
  MSG2MSG(TB_GETANCHORHIGHLIGHT)
  //MSG2MSG(EM_GETTEXTRANGE)
  MSG2MSG(TB_GETBUTTONTEXTW)
  //MSG2MSG(EM_FINDWORDBREAK)
  MSG2MSG(TB_SAVERESTOREW)
  //MSG2MSG(EM_SETOPTIONS)
  MSG2MSG(TB_ADDSTRINGW)
  //MSG2MSG(EM_GETOPTIONS)
  MSG2MSG(TB_MAPACCELERATORA)
  //MSG2MSG(EM_FINDTEXTEX)
  MSG2MSG(TB_GETINSERTMARK)
  //MSG2MSG(EM_GETWORDBREAKPROCEX)
  MSG2MSG(TB_SETINSERTMARK)
  //MSG2MSG(EM_SETWORDBREAKPROCEX)
  MSG2MSG(TB_INSERTMARKHITTEST)
  //MSG2MSG(EM_SETUNDOLIMIT)
  MSG2MSG(TB_MOVEBUTTON)
  MSG2MSG(TB_GETMAXSIZE)
  //MSG2MSG(EM_REDO)
  MSG2MSG(TB_SETEXTENDEDSTYLE)
  //MSG2MSG(EM_CANREDO)
  MSG2MSG(TB_GETEXTENDEDSTYLE)
  //MSG2MSG(EM_GETUNDONAME)
  MSG2MSG(TB_GETPADDING)
  //MSG2MSG(EM_GETREDONAME)
  MSG2MSG(TB_SETPADDING)
  //MSG2MSG(EM_STOPGROUPTYPING)
  MSG2MSG(TB_SETINSERTMARKCOLOR)
  //MSG2MSG(EM_SETTEXTMODE)
  MSG2MSG(TB_GETINSERTMARKCOLOR)
  //MSG2MSG(EM_GETTEXTMODE)
  MSG2MSG(TB_MAPACCELERATORW)
  //MSG2MSG(EM_AUTOURLDETECT)
  MSG2MSG(TB_GETSTRINGW)
  //MSG2MSG(EM_GETAUTOURLDETECT)
  MSG2MSG(TB_GETSTRINGA)
  //MSG2MSG(EM_SETPALETTE)
  //MSG2MSG(EM_GETTEXTEX)
  //MSG2MSG(EM_GETTEXTLENGTHEX)
  //MSG2MSG(EM_SHOWSCROLLBAR)
  //MSG2MSG(EM_SETTEXTEX)
  //MSG2MSG(TAPI_REPLY)
  MSG2MSG(ACM_OPENA)
  //MSG2MSG(BFFM_SETSTATUSTEXTA)
  //MSG2MSG(CDM_FIRST)
  //MSG2MSG(CDM_GETSPEC)
  //MSG2MSG(EM_SETPUNCTUATION)
  //MSG2MSG(IPM_CLEARADDRESS)
  //MSG2MSG(WM_CAP_UNICODE_START)
  MSG2MSG(ACM_PLAY)
  //MSG2MSG(BFFM_ENABLEOK)
  //MSG2MSG(CDM_GETFILEPATH)
  //MSG2MSG(EM_GETPUNCTUATION)
  //MSG2MSG(IPM_SETADDRESS)
  //MSG2MSG(PSM_SETCURSEL)
  //MSG2MSG(UDM_SETRANGE)
  //MSG2MSG(WM_CHOOSEFONT_SETLOGFONT)
  MSG2MSG(ACM_STOP)
  //MSG2MSG(BFFM_SETSELECTIONA)
  //MSG2MSG(CDM_GETFOLDERPATH)
  //MSG2MSG(EM_SETWORDWRAPMODE)
  //MSG2MSG(IPM_GETADDRESS)
  //MSG2MSG(PSM_REMOVEPAGE)
  //MSG2MSG(UDM_GETRANGE)
  //MSG2MSG(WM_CAP_SET_CALLBACK_ERRORW)
  //MSG2MSG(WM_CHOOSEFONT_SETFLAGS)
  MSG2MSG(ACM_OPENW)
  //MSG2MSG(BFFM_SETSELECTIONW)
  //MSG2MSG(CDM_GETFOLDERIDLIST)
  //MSG2MSG(EM_GETWORDWRAPMODE)
  //MSG2MSG(IPM_SETRANGE)
  //MSG2MSG(PSM_ADDPAGE)
  //MSG2MSG(UDM_SETPOS)
  //MSG2MSG(WM_CAP_SET_CALLBACK_STATUSW)
  //MSG2MSG(BFFM_SETSTATUSTEXTW)
  //MSG2MSG(CDM_SETCONTROLTEXT)
  //MSG2MSG(EM_SETIMECOLOR)
  MSG2MSG(IPM_SETFOCUS)
  //MSG2MSG(PSM_CHANGED)
  //MSG2MSG(UDM_GETPOS)
  //MSG2MSG(CDM_HIDECONTROL)
  //MSG2MSG(EM_GETIMECOLOR)
  MSG2MSG(IPM_ISBLANK)
  //MSG2MSG(PSM_RESTARTWINDOWS)
  //MSG2MSG(UDM_SETBUDDY)
  //MSG2MSG(CDM_SETDEFEXT)
  //MSG2MSG(EM_SETIMEOPTIONS)
  MSG2MSG(PSM_REBOOTSYSTEM)
  //MSG2MSG(UDM_GETBUDDY)
  //MSG2MSG(EM_GETIMEOPTIONS)
  MSG2MSG(PSM_CANCELTOCLOSE)
  //MSG2MSG(UDM_SETACCEL)
  //MSG2MSG(EM_CONVPOSITION)
  //MSG2MSG(EM_CONVPOSITION)
  MSG2MSG(PSM_QUERYSIBLINGS)
  //MSG2MSG(UDM_GETACCEL)
  //MSG2MSG(MCIWNDM_GETZOOM)
  MSG2MSG(PSM_UNCHANGED)
  //MSG2MSG(UDM_SETBASE)
  MSG2MSG(PSM_APPLY)
  //MSG2MSG(UDM_GETBASE)
  MSG2MSG(PSM_SETTITLEA)
  //MSG2MSG(UDM_SETRANGE32)
  MSG2MSG(PSM_SETWIZBUTTONS)
  //MSG2MSG(UDM_GETRANGE32)
  //MSG2MSG(WM_CAP_DRIVER_GET_NAMEW)
  MSG2MSG(PSM_PRESSBUTTON)
  //MSG2MSG(UDM_SETPOS32)
  //MSG2MSG(WM_CAP_DRIVER_GET_VERSIONW)
  MSG2MSG(PSM_SETCURSELID)
  //MSG2MSG(UDM_GETPOS32)
  MSG2MSG(PSM_SETFINISHTEXTA)
  MSG2MSG(PSM_GETTABCONTROL)
  MSG2MSG(PSM_ISDIALOGMESSAGE)
  //MSG2MSG(MCIWNDM_REALIZE)
  MSG2MSG(PSM_GETCURRENTPAGEHWND)
  //MSG2MSG(MCIWNDM_SETTIMEFORMATA)
  MSG2MSG(PSM_INSERTPAGE)
  //MSG2MSG(EM_SETLANGOPTIONS)
  //MSG2MSG(MCIWNDM_GETTIMEFORMATA)
  MSG2MSG(PSM_SETTITLEW)
  //MSG2MSG(WM_CAP_FILE_SET_CAPTURE_FILEW)
  //MSG2MSG(EM_GETLANGOPTIONS)
  //MSG2MSG(MCIWNDM_VALIDATEMEDIA)
  MSG2MSG(PSM_SETFINISHTEXTW)
  //MSG2MSG(WM_CAP_FILE_GET_CAPTURE_FILEW)
  //MSG2MSG(EM_GETIMECOMPMODE)
  //MSG2MSG(EM_FINDTEXTW)
  //MSG2MSG(MCIWNDM_PLAYTO)
  //MSG2MSG(WM_CAP_FILE_SAVEASW)
  //MSG2MSG(EM_FINDTEXTEXW)
  //MSG2MSG(MCIWNDM_GETFILENAMEA)
  //MSG2MSG(EM_RECONVERSION)
  //MSG2MSG(MCIWNDM_GETDEVICEA)
  MSG2MSG(PSM_SETHEADERTITLEA)
  //MSG2MSG(WM_CAP_FILE_SAVEDIBW)
  //MSG2MSG(EM_SETIMEMODEBIAS)
  //MSG2MSG(MCIWNDM_GETPALETTE)
  MSG2MSG(PSM_SETHEADERTITLEW)
  //MSG2MSG(EM_GETIMEMODEBIAS)
  //MSG2MSG(MCIWNDM_SETPALETTE)
  MSG2MSG(PSM_SETHEADERSUBTITLEA)
  //MSG2MSG(MCIWNDM_GETERRORA)
  MSG2MSG(PSM_SETHEADERSUBTITLEW)
  MSG2MSG(PSM_HWNDTOINDEX)
  MSG2MSG(PSM_INDEXTOHWND)
  //MSG2MSG(MCIWNDM_SETINACTIVETIMER)
  MSG2MSG(PSM_PAGETOINDEX)
  MSG2MSG(PSM_INDEXTOPAGE)
  MSG2MSG(DL_BEGINDRAG)
  //MSG2MSG(MCIWNDM_GETINACTIVETIMER)
  //MSG2MSG(PSM_IDTOINDEX)
  MSG2MSG(DL_DRAGGING)
  //MSG2MSG(PSM_INDEXTOID)
  MSG2MSG(DL_DROPPED)
  //MSG2MSG(PSM_GETRESULT)
  MSG2MSG(DL_CANCELDRAG)
  //MSG2MSG(PSM_RECALCPAGESIZES)
  //MSG2MSG(MCIWNDM_GET_SOURCE)
  //MSG2MSG(MCIWNDM_PUT_SOURCE)
  //MSG2MSG(MCIWNDM_GET_DEST)
  //MSG2MSG(MCIWNDM_PUT_DEST)
  //MSG2MSG(MCIWNDM_CAN_PLAY)
  //MSG2MSG(MCIWNDM_CAN_WINDOW)
  //MSG2MSG(MCIWNDM_CAN_RECORD)
  //MSG2MSG(MCIWNDM_CAN_SAVE)
  //MSG2MSG(MCIWNDM_CAN_EJECT)
  //MSG2MSG(MCIWNDM_CAN_CONFIG)
  //MSG2MSG(IE_GETINK)
  //MSG2MSG(IE_MSGFIRST)
  //MSG2MSG(MCIWNDM_PALETTEKICK)
  //MSG2MSG(IE_SETINK)
  //MSG2MSG(IE_GETPENTIP)
  //MSG2MSG(IE_SETPENTIP)
  //MSG2MSG(IE_GETERASERTIP)
  //MSG2MSG(IE_SETERASERTIP)
  //MSG2MSG(IE_GETBKGND)
  //MSG2MSG(IE_SETBKGND)
  //MSG2MSG(IE_GETGRIDORIGIN)
  //MSG2MSG(IE_SETGRIDORIGIN)
  //MSG2MSG(IE_GETGRIDPEN)
  //MSG2MSG(IE_SETGRIDPEN)
  //MSG2MSG(IE_GETGRIDSIZE)
  //MSG2MSG(IE_SETGRIDSIZE)
  //MSG2MSG(IE_GETMODE)
  //MSG2MSG(IE_SETMODE)
  //MSG2MSG(IE_GETINKRECT)
  //MSG2MSG(WM_CAP_SET_MCI_DEVICEW)
  //MSG2MSG(WM_CAP_GET_MCI_DEVICEW)
  //MSG2MSG(WM_CAP_PAL_OPENW)
  //MSG2MSG(WM_CAP_PAL_SAVEW)
  //MSG2MSG(IE_GETAPPDATA)
  //MSG2MSG(IE_SETAPPDATA)
  //MSG2MSG(IE_GETDRAWOPTS)
  //MSG2MSG(IE_SETDRAWOPTS)
  //MSG2MSG(IE_GETFORMAT)
  //MSG2MSG(IE_SETFORMAT)
  //MSG2MSG(IE_GETINKINPUT)
  //MSG2MSG(IE_SETINKINPUT)
  //MSG2MSG(IE_GETNOTIFY)
  //MSG2MSG(IE_SETNOTIFY)
  //MSG2MSG(IE_GETRECOG)
  //MSG2MSG(IE_SETRECOG)
  //MSG2MSG(IE_GETSECURITY)
  //MSG2MSG(IE_SETSECURITY)
  //MSG2MSG(IE_GETSEL)
  //MSG2MSG(IE_SETSEL)
  //MSG2MSG(CDM_LAST)
  //MSG2MSG(EM_SETBIDIOPTIONS)
  //MSG2MSG(IE_DOCOMMAND)
  //MSG2MSG(MCIWNDM_NOTIFYMODE)
  //MSG2MSG(EM_GETBIDIOPTIONS)
  //MSG2MSG(IE_GETCOMMAND)
  //MSG2MSG(EM_SETTYPOGRAPHYOPTIONS)
  //MSG2MSG(IE_GETCOUNT)
  //MSG2MSG(EM_GETTYPOGRAPHYOPTIONS)
  //MSG2MSG(IE_GETGESTURE)
  //MSG2MSG(MCIWNDM_NOTIFYMEDIA)
  //MSG2MSG(EM_SETEDITSTYLE)
  //MSG2MSG(IE_GETMENU)
  //MSG2MSG(EM_GETEDITSTYLE)
  //MSG2MSG(IE_GETPAINTDC)
  //MSG2MSG(MCIWNDM_NOTIFYERROR)
  //MSG2MSG(IE_GETPDEVENT)
  //MSG2MSG(IE_GETSELCOUNT)
  //MSG2MSG(IE_GETSELITEMS)
  //MSG2MSG(IE_GETSTYLE)
  //MSG2MSG(MCIWNDM_SETTIMEFORMATW)
  //MSG2MSG(EM_OUTLINE)
  //MSG2MSG(MCIWNDM_GETTIMEFORMATW)
  //MSG2MSG(EM_GETSCROLLPOS)
  //MSG2MSG(EM_SETSCROLLPOS)
  //MSG2MSG(EM_SETSCROLLPOS)
  //MSG2MSG(EM_SETFONTSIZE)
  MSG2MSG(EM_GETZOOM)
  //MSG2MSG(MCIWNDM_GETFILENAMEW)
  MSG2MSG(EM_SETZOOM)
  //MSG2MSG(MCIWNDM_GETDEVICEW)
  //MSG2MSG(EM_GETVIEWKIND)
  //MSG2MSG(EM_SETVIEWKIND)
  //MSG2MSG(EM_GETPAGE)
  //MSG2MSG(MCIWNDM_GETERRORW)
  //MSG2MSG(EM_SETPAGE)
  //MSG2MSG(EM_GETHYPHENATEINFO)
  //MSG2MSG(EM_SETHYPHENATEINFO)
  //MSG2MSG(EM_GETPAGEROTATE)
  //MSG2MSG(EM_SETPAGEROTATE)
  //MSG2MSG(EM_GETCTFMODEBIAS)
  //MSG2MSG(EM_SETCTFMODEBIAS)
  //MSG2MSG(EM_GETCTFOPENSTATUS)
  //MSG2MSG(EM_SETCTFOPENSTATUS)
  //MSG2MSG(EM_GETIMECOMPTEXT)
  //MSG2MSG(EM_ISIME)
  //MSG2MSG(EM_GETIMEPROPERTY)
  //MSG2MSG(EM_GETQUERYRTFOBJ)
  //MSG2MSG(EM_SETQUERYRTFOBJ)
  //MSG2MSG(FM_GETFOCUS)
  //MSG2MSG(FM_GETDRIVEINFOA)
  //MSG2MSG(FM_GETSELCOUNT)
  //MSG2MSG(FM_GETSELCOUNTLFN)
  //MSG2MSG(FM_GETFILESELA)
  //MSG2MSG(FM_GETFILESELLFNA)
  //MSG2MSG(FM_REFRESH_WINDOWS)
  //MSG2MSG(FM_RELOAD_EXTENSIONS)
  //MSG2MSG(FM_GETDRIVEINFOW)
  //MSG2MSG(FM_GETFILESELW)
  //MSG2MSG(FM_GETFILESELLFNW)
  //MSG2MSG(WLX_WM_SAS)
  //MSG2MSG(SM_GETSELCOUNT)
  //MSG2MSG(UM_GETSELCOUNT)
  //MSG2MSG(WM_CPL_LAUNCH)
  //MSG2MSG(SM_GETSERVERSELA)
  //MSG2MSG(UM_GETUSERSELA)
  //MSG2MSG(WM_CPL_LAUNCHED)
  //MSG2MSG(SM_GETSERVERSELW)
  //MSG2MSG(UM_GETUSERSELW)
  //MSG2MSG(SM_GETCURFOCUSA)
  //MSG2MSG(UM_GETGROUPSELA)
  //MSG2MSG(SM_GETCURFOCUSW)
  //MSG2MSG(UM_GETGROUPSELW)
  //MSG2MSG(SM_GETOPTIONS)
  //MSG2MSG(UM_GETCURFOCUSA)
  //MSG2MSG(UM_GETCURFOCUSW)
  //MSG2MSG(UM_GETOPTIONS)
  //MSG2MSG(UM_GETOPTIONS2)
  MSG2MSG(LVM_FIRST)
  //MSG2MSG(LVM_GETBKCOLOR)
  MSG2MSG(LVM_SETBKCOLOR)
  MSG2MSG(LVM_GETIMAGELIST)
  MSG2MSG(LVM_SETIMAGELIST)
  MSG2MSG(LVM_GETITEMCOUNT)
  MSG2MSG(LVM_GETITEMA)
  MSG2MSG(LVM_SETITEMA)
  MSG2MSG(LVM_INSERTITEMA)
  MSG2MSG(LVM_DELETEITEM)
  MSG2MSG(LVM_DELETEALLITEMS)
  MSG2MSG(LVM_GETCALLBACKMASK)
  MSG2MSG(LVM_SETCALLBACKMASK)
  MSG2MSG(LVM_GETNEXTITEM)
  MSG2MSG(LVM_FINDITEMA)
  MSG2MSG(LVM_GETITEMRECT)
  MSG2MSG(LVM_SETITEMPOSITION)
  MSG2MSG(LVM_GETITEMPOSITION)
  MSG2MSG(LVM_GETSTRINGWIDTHA)
  MSG2MSG(LVM_HITTEST)
  MSG2MSG(LVM_ENSUREVISIBLE)
  MSG2MSG(LVM_SCROLL)
  MSG2MSG(LVM_REDRAWITEMS)
  MSG2MSG(LVM_ARRANGE)
  MSG2MSG(LVM_EDITLABELA)
  MSG2MSG(LVM_GETEDITCONTROL)
  MSG2MSG(LVM_GETCOLUMNA)
  MSG2MSG(LVM_SETCOLUMNA)
  MSG2MSG(LVM_INSERTCOLUMNA)
  MSG2MSG(LVM_DELETECOLUMN)
  MSG2MSG(LVM_GETCOLUMNWIDTH)
  MSG2MSG(LVM_SETCOLUMNWIDTH)
  MSG2MSG(LVM_GETHEADER)
  MSG2MSG(LVM_CREATEDRAGIMAGE)
  MSG2MSG(LVM_GETVIEWRECT)
  MSG2MSG(LVM_GETTEXTCOLOR)
  MSG2MSG(LVM_SETTEXTCOLOR)
  MSG2MSG(LVM_GETTEXTBKCOLOR)
  MSG2MSG(LVM_SETTEXTBKCOLOR)
  MSG2MSG(LVM_GETTOPINDEX)
  MSG2MSG(LVM_GETCOUNTPERPAGE)
  MSG2MSG(LVM_GETORIGIN)
  MSG2MSG(LVM_UPDATE)
  MSG2MSG(LVM_SETITEMSTATE)
  MSG2MSG(LVM_GETITEMSTATE)
  MSG2MSG(LVM_GETITEMTEXTA)
  MSG2MSG(LVM_SETITEMTEXTA)
  MSG2MSG(LVM_SETITEMCOUNT)
  MSG2MSG(LVM_SORTITEMS)
  MSG2MSG(LVM_SETITEMPOSITION32)
  MSG2MSG(LVM_GETSELECTEDCOUNT)
  MSG2MSG(LVM_GETITEMSPACING)
  MSG2MSG(LVM_GETISEARCHSTRINGA)
  MSG2MSG(LVM_SETICONSPACING)
  MSG2MSG(LVM_SETEXTENDEDLISTVIEWSTYLE)
  MSG2MSG(LVM_GETEXTENDEDLISTVIEWSTYLE)
  MSG2MSG(LVM_GETSUBITEMRECT)
  MSG2MSG(LVM_SUBITEMHITTEST)
  MSG2MSG(LVM_SETCOLUMNORDERARRAY)
  MSG2MSG(LVM_GETCOLUMNORDERARRAY)
  MSG2MSG(LVM_SETHOTITEM)
  MSG2MSG(LVM_GETHOTITEM)
  MSG2MSG(LVM_SETHOTCURSOR)
  MSG2MSG(LVM_GETHOTCURSOR)
  MSG2MSG(LVM_APPROXIMATEVIEWRECT)
  MSG2MSG(LVM_SETWORKAREAS)
  MSG2MSG(LVM_GETSELECTIONMARK)
  MSG2MSG(LVM_SETSELECTIONMARK)
  MSG2MSG(LVM_SETBKIMAGEA)
  MSG2MSG(LVM_GETBKIMAGEA)
  MSG2MSG(LVM_GETWORKAREAS)
  MSG2MSG(LVM_SETHOVERTIME)
  MSG2MSG(LVM_GETHOVERTIME)
  MSG2MSG(LVM_GETNUMBEROFWORKAREAS)
  MSG2MSG(LVM_SETTOOLTIPS)
  MSG2MSG(LVM_GETITEMW)
  MSG2MSG(LVM_SETITEMW)
  MSG2MSG(LVM_INSERTITEMW)
  MSG2MSG(LVM_GETTOOLTIPS)
  MSG2MSG(LVM_FINDITEMW)
  MSG2MSG(LVM_GETSTRINGWIDTHW)
  MSG2MSG(LVM_GETCOLUMNW)
  MSG2MSG(LVM_SETCOLUMNW)
  MSG2MSG(LVM_INSERTCOLUMNW)
  MSG2MSG(LVM_GETITEMTEXTW)
  MSG2MSG(LVM_SETITEMTEXTW)
  MSG2MSG(LVM_GETISEARCHSTRINGW)
  MSG2MSG(LVM_EDITLABELW)
  MSG2MSG(LVM_GETBKIMAGEW)
  MSG2MSG(LVM_SETSELECTEDCOLUMN)
  //MSG2MSG(LVM_SETTILEWIDTH)
  MSG2MSG(LVM_SETVIEW)
  MSG2MSG(LVM_GETVIEW)
  MSG2MSG(LVM_INSERTGROUP)
  MSG2MSG(LVM_SETGROUPINFO)
  MSG2MSG(LVM_GETGROUPINFO)
  MSG2MSG(LVM_REMOVEGROUP)
  MSG2MSG(LVM_MOVEGROUP)
  MSG2MSG(LVM_MOVEITEMTOGROUP)
  MSG2MSG(LVM_SETGROUPMETRICS)
  MSG2MSG(LVM_GETGROUPMETRICS)
  MSG2MSG(LVM_ENABLEGROUPVIEW)
  MSG2MSG(LVM_SORTGROUPS)
  MSG2MSG(LVM_INSERTGROUPSORTED)
  MSG2MSG(LVM_REMOVEALLGROUPS)
  MSG2MSG(LVM_HASGROUP)
  MSG2MSG(LVM_SETTILEVIEWINFO)
  MSG2MSG(LVM_GETTILEVIEWINFO)
  MSG2MSG(LVM_SETTILEINFO)
  MSG2MSG(LVM_GETTILEINFO)
  MSG2MSG(LVM_SETINSERTMARK)
  MSG2MSG(LVM_GETINSERTMARK)
  MSG2MSG(LVM_INSERTMARKHITTEST)
  MSG2MSG(LVM_GETINSERTMARKRECT)
  MSG2MSG(LVM_SETINSERTMARKCOLOR)
  MSG2MSG(LVM_GETINSERTMARKCOLOR)
  MSG2MSG(LVM_SETINFOTIP)
  MSG2MSG(LVM_GETSELECTEDCOLUMN)
  MSG2MSG(LVM_ISGROUPVIEWENABLED)
  MSG2MSG(LVM_GETOUTLINECOLOR)
  MSG2MSG(LVM_SETOUTLINECOLOR)
  MSG2MSG(LVM_CANCELEDITLABEL)
  MSG2MSG(LVM_MAPINDEXTOID)
  MSG2MSG(LVM_MAPIDTOINDEX)
  MSG2MSG(LVM_ISITEMVISIBLE)
  MSG2MSG(LVM_GETEMPTYTEXT)
  MSG2MSG(LVM_GETFOOTERRECT)
  MSG2MSG(LVM_GETFOOTERINFO)
  MSG2MSG(LVM_GETFOOTERITEMRECT)
  MSG2MSG(LVM_GETFOOTERITEM)
  MSG2MSG(LVM_GETITEMINDEXRECT)
  MSG2MSG(LVM_SETITEMINDEXSTATE)
  MSG2MSG(LVM_GETNEXTITEMINDEX)
  MSG2MSG(CCM_FIRST)
  //MSG2MSG(OCM__BASE)
  MSG2MSG(CCM_SETBKCOLOR)
  MSG2MSG(CCM_SETCOLORSCHEME)
  MSG2MSG(CCM_GETCOLORSCHEME)
  MSG2MSG(CCM_GETDROPTARGET)
  MSG2MSG(CCM_SETUNICODEFORMAT)
  //MSG2MSG(LVM_SETUNICODEFORMAT)
  MSG2MSG(CCM_GETUNICODEFORMAT)
  //MSG2MSG(LVM_GETUNICODEFORMAT)
  MSG2MSG(CCM_SETVERSION)
  MSG2MSG(CCM_GETVERSION)
  MSG2MSG(CCM_SETNOTIFYWINDOW)
  MSG2MSG(CCM_SETWINDOWTHEME)
  MSG2MSG(CCM_DPISCALE)
  //MSG2MSG(OCM_CTLCOLOR)
  //MSG2MSG(OCM_DRAWITEM)
  //MSG2MSG(OCM_MEASUREITEM)
  //MSG2MSG(OCM_DELETEITEM)
  //MSG2MSG(OCM_VKEYTOITEM)
  //MSG2MSG(OCM_CHARTOITEM)
  //MSG2MSG(OCM_COMPAREITEM)
  //MSG2MSG(OCM_NOTIFY)
  //MSG2MSG(OCM_COMMAND)
  //MSG2MSG(OCM_HSCROLL)
  //MSG2MSG(OCM_VSCROLL)
  //MSG2MSG(OCM_CTLCOLORMSGBOX)
  //MSG2MSG(OCM_CTLCOLOREDIT)
  //MSG2MSG(OCM_CTLCOLORLISTBOX)
  //MSG2MSG(OCM_CTLCOLORBTN)
  //MSG2MSG(OCM_CTLCOLORDLG)
  //MSG2MSG(OCM_CTLCOLORSCROLLBAR)
  //MSG2MSG(OCM_CTLCOLORSTATIC)
  //MSG2MSG(OCM_PARENTNOTIFY)
  //MSG2MSG(OCM_PARENTNOTIFY)
  MSG2MSG(MN_GETHMENU)
  MSG2MSG(WM_APP)
  MSG2MSG(WM_DWMNCRENDERINGCHANGED)
  MSG2MSG(WM_TASKBARBUTTONCREATED)
  MSG2MSG(WM_MSIMEQUERYPOSITION)
  MSG2MSG(WM_GETTITLEBARINFOEX)
  //MSG2MSG(WM_RASDIALEVENT)
  default:
    return TEXT("Unexpected MSG!\n");
  }
#undef MSG2MSG
}

EXTERN_C
LPCTSTR FORCEINLINE
DecipherSysCommand(
    UINT cmd)
{
#define CMD2CMD(x)     \
    case x:            \
        return TEXT(#x) TEXT("\n");

    switch(GET_SC_WPARAM(cmd)) {
    CMD2CMD(SC_SIZE)
    CMD2CMD(SC_MOVE)
    CMD2CMD(SC_MINIMIZE)
    CMD2CMD(SC_MAXIMIZE)
    CMD2CMD(SC_NEXTWINDOW)
    CMD2CMD(SC_PREVWINDOW)
    CMD2CMD(SC_CLOSE)
    CMD2CMD(SC_VSCROLL)
    CMD2CMD(SC_HSCROLL)
    CMD2CMD(SC_MOUSEMENU)
    CMD2CMD(SC_KEYMENU)
    CMD2CMD(SC_RESTORE)
    CMD2CMD(SC_TASKLIST)
    CMD2CMD(SC_SCREENSAVE)
    CMD2CMD(SC_HOTKEY)
    CMD2CMD(SC_DEFAULT)
    CMD2CMD(SC_MONITORPOWER)
    CMD2CMD(SC_CONTEXTHELP)
    CMD2CMD(SC_SEPARATOR)
    CMD2CMD(SCF_ISSECURE)
    default:
        return TEXT("Unexpected CMD!");
    }

#undef CMD2CMD
}

BOOL CALLBACK EnumChildProc(HWND hwndChild, LPARAM lParam)
{
    LPWINDOWPOS lpwpos;
    RECT rcChild;

    lpwpos = (LPWINDOWPOS)lParam;

    GetWindowRect(hwndChild, &rcChild);
    SetWindowPos(hwndChild, 0,
      lpwpos->x + (0.5f * (lpwpos->cx - labs(rcChild.right - rcChild.left))),
      lpwpos->y + (0.5f * (lpwpos->cy - labs(rcChild.right - rcChild.left))), 0, 0,
      SWP_SHOWWINDOW | SWP_NOSIZE | SWP_NOACTIVATE | SWP_NOOWNERZORDER | SWP_FRAMECHANGED);
    return FALSE;
}

EXTERN_C
HWND FORCEINLINE
GetRealParent(
    HWND hWnd)
{
    HWND hParent;

    hParent = GetAncestor(hWnd, GA_PARENT);
    if ((!hParent) || (hParent == GetDesktopWindow()))
      return NULL;

    return hParent;
}

HWND WINAPI
CreateWindowServer(
    void)
{
    SERVERLAUNCHSYNACK     launchSynAck;
    HANDLE                 hServerThread;
    DWORD                  dwServerThreadId;
    LPTHREAD_START_ROUTINE lpStartRoutine = (LPTHREAD_START_ROUTINE)ServerThread;

    RtlSecureZeroMemory(&launchSynAck, sizeof(launchSynAck));

    launchSynAck.dwHostThreadId = GetCurrentThreadId();

    if (launchSynAck.hServerAck = CreateEvent(0, 0, 0, 0))
    {
      if (hServerThread = CreateThread(0, 0, lpStartRoutine, &launchSynAck, CREATE_SUSPENDED, &dwServerThreadId))
      {
        ResumeThread(hServerThread);
      
        WaitForSingleObject(launchSynAck.hServerAck, INFINITE);

        CloseHandle(hServerThread);
      }

      CloseHandle(launchSynAck.hServerAck);
    }

    return launchSynAck.hServer;
}

HWND WINAPI
ServerCreateWindow(
    HWND hwndServer,
    LPCREATEWINDOWPARAMS lpcwp)
{
    return (HWND)SendMessage(hwndServer, WM_SERVERCREATEWINDOW, (WPARAM)lpcwp, 0);
}

/* void Cls_OnExitSizeMove(HWND hwnd */
#define HANDLE_WM_SERVERACK(hwnd, wParam, lParam, fn) \
        (LRESULT)((fn)((hwnd), (LPCREATEWINDOWPARAMS)(wParam)))

/* void Cls_OnExitSizeMove(HWND hwnd */
#define HANDLE_WM_SERVERCREATEWINDOW(hwnd, wParam, lParam, fn) \
        (LRESULT)((fn)((hwnd), (LPCREATEWINDOWPARAMS)(wParam)))

/* void Cls_OnExitSizeMove(HWND hwnd */
#define HANDLE_WM_SERVERDESTROYWINDOW(hwnd, wParam, lParam, fn) \
        (LRESULT)((fn)((hwnd), (HWND)(wParam)))

#define HANDLE_WM_SERVERDESTROYWINDOW(hwnd, wParam, lParam, fn) \
        (LRESULT)((fn)((hwnd), (HWND)(wParam)))

LRESULT WINAPI CALLBACK 
DefServerProc(
    HWND   hWnd, 
    UINT   uMsg,
    WPARAM wParam,
    LPARAM lParam)
{
    switch(uMsg) {
    HANDLE_MSG(hWnd, WM_NCCREATE,            OnNCCreate);
    HANDLE_MSG(hWnd, WM_SERVERCREATEWINDOW,  OnServerCreateWindow);
    HANDLE_MSG(hWnd, WM_SERVERDESTROYWINDOW, OnServerDestroyWindow);
    FORWARD_MSG(hWnd, uMsg, wParam, lParam,  DefWindowProc);
    }
}

EXTERN_C
BOOL FORCEINLINE WINAPI
MonitorWorkRectFromWindow(
    HWND   hwnd,
    LPRECT lprcWork)
{
    MONITORINFO mi = { sizeof(mi) };
    
    if (GetMonitorInfo(MonitorFromWindow(hwnd, MONITOR_DEFAULTTONEAREST), (LPMONITORINFO)&mi))
      return CopyRect(lprcWork, &mi.rcWork);

    return FALSE;
}

EXTERN_C
BOOL FORCEINLINE WINAPI
GetWindowCenteredPoint(
    LPPOINT      lppt,
    const LPSIZE lpsz)
{
    MONITORINFO mi = { sizeof(mi) };

    if (GetMonitorInfo(MonitorFromPoint(*lppt, MONITOR_DEFAULTTONEAREST), (LPMONITORINFO)&mi))
    {
      lppt->x = (LONG)(mi.rcWork.left + (0.5f * (ABS(mi.rcWork.right - mi.rcWork.left) - lpsz->cx)));
      lppt->y = (LONG)(mi.rcWork.top  + (0.5f * (ABS(mi.rcWork.bottom - mi.rcWork.top) - lpsz->cy)));

      return TRUE;
    }

    return FALSE;
}

EXTERN_C
HRESULT PFORCEINLINE WINAPI
EnableBlurBehind(
    HWND hWnd)
{
    HRESULT hr = E_FAIL;
    HRGN hRgn;

    if (hRgn = CreateRectRgn(0, 0, -1, -1))
    {
      DWM_BLURBEHIND bb = 
        (DWM_BLURBEHIND) { DWM_BB_ENABLE | DWM_BB_BLURREGION, TRUE, hRgn };

      hr = DwmEnableBlurBehindWindow(hWnd, &bb);

      DeleteRgn(hRgn);
    }

    return hr;
}

EXTERN_C
BOOL CFORCEINLINE WINAPI
ShowSystemMenu(
    HWND hwnd,
    int x,
    int y)
{
    BOOL  fCommand;
    POINT ptCursor;
    HMENU hMenu2 = (HMENU)SendMessage(hwnd, MN_GETHMENU, 0, 0);
    SetMenuDefaultItem(hMenu2, -1, TRUE);
    HMENU hMenu = GetSystemMenu(hwnd, FALSE);
    UINT  uFlags = TPM_LEFTALIGN | TPM_TOPALIGN | TPM_RETURNCMD;
    
    GetCursorPos(&ptCursor);
    SetMenuDefaultItem(hMenu, -1, TRUE);

    if(fCommand = TrackPopupMenuEx(hMenu, uFlags, ptCursor.x, ptCursor.y, hwnd, 0))
    {
      PostMessage(hwnd, WM_SYSCOMMAND, (WPARAM)fCommand, 0);
    }
}

EXTERN_C
VOID PFORCEINLINE WINAPI
EnableDarkMode(
    HWND hWnd)
{
  SetPreferredAppMode(PAM_ALLOWDARK);
  SetProp(hWnd, TEXT("UseImmersiveDarkModeColors"), (HANDLE)1);
  //SetWindowTheme(hWnd, L"DarkMode_Explorer", 0);
  SetWindowTheme(hWnd, L"DWMWindow", 0);
  //SetWindowTheme(hWnd, L" ", L" ");

  //RefreshImmersiveColorPolicyState();
}

EXTERN_C
VOID PFORCEINLINE WINAPI
EnableLightMode(
    HWND hWnd)
{
  SetPreferredAppMode(PAM_DEFAULT);
  SetProp(hWnd, TEXT("UseImmersiveDarkModeColors"), (HANDLE)0);
  //SetWindowTheme(hWnd, L"Explorer", 0);
  SetWindowTheme(hWnd, L"DWMWindow", 0);
  //SetWindowTheme(hWnd, L" ", L" ");

  //RefreshImmersiveColorPolicyState();
}

PFNSETPREFERREDAPPMODE SetPreferredAppMode;
PFNREFRESHIMMERSIVECOLORPOLICYSTATE RefreshImmersiveColorPolicyState;

EXTERN_C
BOOL FORCEINLINE WINAPI
InitializeSysThunks(
    VOID)
{
    HMODULE __user32  = GetModuleHandle(TEXT("user32.dll"));
    HMODULE __uxtheme = GetModuleHandle(TEXT("UxTheme.dll"));

    if (NULL != __user32)
    {
      SetWindowCompositionAttribute = (PFNSETWINDOWCOMPOSITIONATTRIBUTE)GetProcAddress(__user32, "SetWindowCompositionAttribute");
    }
    
    if (NULL != __uxtheme)
    {
       SetPreferredAppMode = (PFNSETPREFERREDAPPMODE)GetProcAddress(__uxtheme, MAKEINTRESOURCEA(135));
       RefreshImmersiveColorPolicyState = (PFNREFRESHIMMERSIVECOLORPOLICYSTATE)GetProcAddress(__uxtheme, MAKEINTRESOURCEA(104));
    }

    return !!SetWindowCompositionAttribute && !!SetPreferredAppMode;
}

static
ATOM FORCEINLINE WINAPI
RegisterServerClass(
    void)
{
    WNDCLASS wc = { sizeof(wc) };
    
    wc.style         = CS_GLOBALCLASS;
    wc.lpfnWndProc   = DefServerProc;
    wc.lpszClassName = HWNDSERVER_CLASS;
    
    return RegisterClass(&wc);
}

EXTERN_C
BOOL FORCEINLINE WINAPI
SetWindowData(
    HWND hWnd,
    int nIndex,
    LPVOID pData)
{
    LONG_PTR offset;

    SetLastError(NO_ERROR);
    offset = SetWindowLongPtr(hWnd, nIndex, (LONG_PTR)pData);
    return !((0 == offset) && (NO_ERROR != GetLastError()));
}

EXTERN_C
NCHIT PFORCEINLINE WINAPI
NCHitTest(
    HWND hwnd,
    POINT pt)
{
    RECT rcWindow;
    RECT rcBounds;
    SIZE border;
    UINT dpi;
    const BOOL fIsMaximized = IsMaximized(hwnd);

    GetWindowRect(hwnd, &rcWindow);
    GetWindowBorders(hwnd, &border);
    dpi = GetDpiForWindow(hwnd);
    
    DwmGetWindowAttribute(hwnd, DWMWA_EXTENDED_FRAME_BOUNDS, &rcBounds, sizeof(rcBounds));

    int bx = 0.5f * (RECTWIDTH(rcWindow) - RECTWIDTH(rcBounds));
    int by = 0.5f * (RECTHEIGHT(rcWindow) - RECTHEIGHT(rcBounds));

    return NCHIT_LEFT   * (pt.x == CLAMP(pt.x, rcWindow.left, rcWindow.left + ((border.cx + 5) * !fIsMaximized))) |
           NCHIT_TOP    * (pt.y == CLAMP(pt.y, rcWindow.top - 2,  rcWindow.top + ((border.cy + 5 )* !fIsMaximized))) |
           NCHIT_RIGHT  * (pt.x == CLAMP(pt.x, rcWindow.right  - ((border.cx + 5) * !fIsMaximized), rcWindow.right)) |
           NCHIT_BOTTOM * (pt.y == CLAMP(pt.y, rcWindow.bottom - 5, rcWindow.bottom + border.cy));

}

EXTERN_C
BOOL PFORCEINLINE APIPRIVATE
GetCaptionButtonRect(
    HWND   hWnd,
    LPRECT lprcCaption,
    CAPTIONBUTTON  eCaptionButton)
{
    if (GetCaptionRect(hWnd, lprcCaption))
    {
      UINT nDpi = GetDpiForWindow(hWnd);
      int nWidth = MulDiv(45, nDpi, 96);

      switch (eCaptionButton) {
      case CB_CLOSEBUTTON:
        lprcCaption->left = (lprcCaption->right - nWidth) + 1;
        break;
      case CB_MAXBUTTON:
        lprcCaption->left = (lprcCaption->right - nWidth) + 1;
        lprcCaption->left  -= (nWidth + 1);
        lprcCaption->right -= (nWidth + 1);
        break;
      case CB_MINBUTTON:
        lprcCaption->left = (lprcCaption->right - nWidth) + 1;
        lprcCaption->left  -= (2 * nWidth) + 1;
        lprcCaption->right -= (2 * nWidth) + 1;
        break;
      case CB_LIGHTDARKBUTTON:
        lprcCaption->left = (lprcCaption->right - nWidth) + 1;
        lprcCaption->left  -= (3 * nWidth) + 1;
        lprcCaption->right -= (3 * nWidth) + 1;
        break;
      default:
        return FALSE;
      }

      return TRUE;
    }

    return FALSE;
}

EXTERN_C
BOOL PFORCEINLINE APIPRIVATE
GetCaptionButtonRectFast(
    LPRECT lprcCaption,
    int nWidth,
    CAPTIONBUTTON eCaptionButton)
{
    if (lprcCaption)
    {
      switch (eCaptionButton) {
      case CB_CLOSEBUTTON:
        lprcCaption->left = (lprcCaption->right - nWidth) + 1;
        break;
      case CB_MAXBUTTON:
        lprcCaption->left = (lprcCaption->right - nWidth) + 1;
        lprcCaption->left  -= (nWidth + 1);
        lprcCaption->right -= (nWidth + 1);
        break;
      case CB_MINBUTTON:
        lprcCaption->left = (lprcCaption->right - nWidth) + 1;
        lprcCaption->left  -= (2 * nWidth) + 1;
        lprcCaption->right -= (2 * nWidth) + 1;
        break;
      case CB_LIGHTDARKBUTTON:
        lprcCaption->left = (lprcCaption->right - nWidth) + 1;
        lprcCaption->left  -= (3 * nWidth) + 1;
        lprcCaption->right -= (3 * nWidth) + 1;
        break;
      default:
        return FALSE;
      }

      return TRUE;
    }

    return FALSE;
}

EXTERN_C
BOOL WINAPI
IsWindowClosing(
    HWND hwnd)
{
    if (hwnd == NULL)
        return TRUE;

    /* If the handle is no longer valid, the window is closing or gone */
    if (!IsWindow(hwnd))
        return TRUE;

    /* During teardown GWLP_WNDPROC can become NULL */
    if (GetWindowLongPtr(hwnd, GWLP_WNDPROC) == 0)
        return TRUE;

    return FALSE;
}

HWND ShowTooltip(const char* szTip, int x, int y)
{
    HWND hwndTip;
    TOOLINFO ti;

    hwndTip = CreateWindowExA(
        WS_EX_TOPMOST,
        TOOLTIPS_CLASSA,
        NULL,
        WS_POPUP | TTS_NOPREFIX | TTS_ALWAYSTIP,
        CW_USEDEFAULT,
        CW_USEDEFAULT,
        CW_USEDEFAULT,
        CW_USEDEFAULT,
        NULL,
        NULL,
        GetModuleHandleA(NULL),
        NULL
    );

    if (!hwndTip)
        return NULL;

    SetWindowPos(hwndTip, HWND_TOPMOST, 0,0,0,0,
        SWP_NOMOVE | SWP_NOSIZE | SWP_NOACTIVATE);

    ZeroMemory(&ti, sizeof(ti));
    ti.cbSize = sizeof(ti);
    ti.uFlags = TTF_TRACK | TTF_ABSOLUTE;
    ti.hwnd = NULL;
    ti.uId = 0;
    ti.lpszText = (LPSTR)szTip;

    SendMessage(hwndTip, TTM_ADDTOOLA, 0, (LPARAM)&ti);
    SendMessage(hwndTip, TTM_TRACKPOSITION, 0, (LPARAM)MAKELONG(x, y));
    SendMessage(hwndTip, TTM_TRACKACTIVATE, TRUE, (LPARAM)&ti);

    return hwndTip;
}

VOID DestroyTooltip(HWND hwnd)
{
    if (!hwnd)
        return;

    TOOLINFO ti;
    ZeroMemory(&ti, sizeof(ti));
    ti.cbSize = sizeof(ti);

    SendMessage(hwnd, TTM_TRACKACTIVATE, FALSE, (LPARAM)&ti);
    DestroyWindow(hwnd);
}

BOOL IsRestoredEx(HWND hwnd)
{
    BOOL fIsRestored = FALSE;

    if (hwnd && IsWindow(hwnd))
    {
      RECT rcWindow;
      WINDOWPLACEMENT wp = { sizeof(wp) };

      if (GetWindowPlacement(hwnd, &wp))
        if (wp.showCmd == SW_SHOWNORMAL)
          if (GetWindowRect(hwnd, &rcWindow) && WorkspaceToScreen(&wp.rcNormalPosition))
            fIsRestored = EqualRect(&rcWindow, &wp.rcNormalPosition);
    }

    return fIsRestored;
}

BOOL WorkspaceToScreen(LPRECT lprcWorkspace)
{
    MONITORINFO mi;
    HMONITOR hmon;
    int dx, dy;

    if (!lprcWorkspace)
        return FALSE;

    mi.cbSize = sizeof(mi);

    /* Find the monitor the rect belongs to */
    hmon = MonitorFromRect(lprcWorkspace, MONITOR_DEFAULTTONEAREST);
    if (!hmon)
        return FALSE;

    if (!GetMonitorInfo(hmon, &mi))
        return FALSE;

    /* Workspace origin offset */
    dx = mi.rcWork.left - mi.rcMonitor.left;
    dy = mi.rcWork.top  - mi.rcMonitor.top;

    OffsetRect(lprcWorkspace, dx, dy);

    return TRUE;
}

BOOL DwmGetWindowAttributes(
    HWND hwnd,
    PDWM_WINDOW_ATTRIBUTES pAttr)
{
    BOOL fSuccess = TRUE;

    if (hwnd && pAttr && IsWindow(hwnd))
    {
      fSuccess &= SUCCEEDED(DwmGetWindowAttribute(hwnd, DWMWA_NCRENDERING_ENABLED, &pAttr->fNcRenderingEnabled, sizeof(pAttr->fNcRenderingEnabled)));
      fSuccess &= SUCCEEDED(DwmGetWindowAttribute(hwnd, DWMWA_CAPTION_BUTTON_BOUNDS, &pAttr->rcCaptionButtonBounds, sizeof(pAttr->rcCaptionButtonBounds)));
      fSuccess &= SUCCEEDED(DwmGetWindowAttribute(hwnd, DWMWA_EXTENDED_FRAME_BOUNDS, &pAttr->rcExtendedFrameBounds, sizeof(pAttr->rcExtendedFrameBounds)));
      fSuccess &= SUCCEEDED(DwmGetWindowAttribute(hwnd, DWMWA_CLOAKED, &pAttr->fCloaked, sizeof(pAttr->fCloaked)));
    }

    return fSuccess;
}

EXTERN_C
LRESULT PFORCEINLINE
DwmDefWindowProcEx(
    HWND   hWnd,
    UINT   uMsg,
    WPARAM wParam,
    LPARAM lParam)
{
    LRESULT lResult;

    if (!DwmDefWindowProc(hWnd, uMsg, wParam, lParam, &lResult))
      lResult = MAXLONG;
    return lResult;
}